### ISSUE TITLE
Missing translations & typos

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#327]
## 1. Barre de menus
- [x] draw feature -> missing translation in French and English
- [x] Fenêtre d'identification: titre -> Profil de l'utilisateur
- [x] dashboard -> tableau de bord
- [x] reset bearing -> réinitialiser l'orientation
- [x] A propos: le disclaimer n'est pas traduit.
- [x] Map composer: le tooltip n'est pas traduit (btn_map_composer)
- [x] Draw polygon: le tooltip n'est pas traduit (btn_draw_mode)

### 2.1 Types de vues
- [x] overlap -> chevauchement
- [x] dashboard -> tableau de bord
- [x] time slider -> curseur temporel
- [x] story map -> récit [edit : carte narrative]

### 3.1 Préférences
- [x] filter values -> filtrer les valeurs [edit: changed as label, set 'Filtrer par valeurs']

### 3.2 Afficher les métadonnées
- [x] close button -> fermer
- [x] META_VIEW_PROJECT -> id du projet
- [x] META_VIEW_PROJECTS -> id des projets partagés
- [x] Les intitulés des différentes catégories ne sont pas traduites. On a juste les ids/clés.

#### 3.3.1 Vecteur: visualiser le résumé de la source
- [x] titre pop-up: Layer summary -> résumé de la source
- [ ] ~~dans le pop-up: summary -> résumé~~
#### 3.3.2 Raster
- [x] titre du WMS generator ('WMS URL helper') et le nom de l'outil à activer ('Display WMS tools')

### 3.4 Editer le dashboard
- [x] boutons en dessous des widgets non traduits
- [x] titre du pop-up: Edit dashboard -> Editer le tableau de board
- [x] dans le pop-up: dashboard -> tableau de bord
- [x] traduire le tooltip -> Editer le tableau de board

### 3.5 Configurer le style de cette vue
- [x] Après l'ajout d'une règle, l'option de supprimer est traduit en "Last Règle" au lieu de "Dernière Règle".
- [x] custom style -> style personnalisé
- [ ] modifier "opacité" en "transparence" pour être cohérent avec le reste de l'application #470
- [x] titre pop-up: Edit Style -> Editer le style de la vue
- [x] L'outil color picker n'est pas traduits.

### 3.6 Partager cette vue
- [x] Tout le pop-up est non traduit.

### 3.7 Validation des métadonnées (triangle orange)
- [x] Source missing -> Missing source #414
- [x] close button -> fermer

### 3.8 Score d'intégrité (étoile)
- [x] le tooltip n'est pas traduit.
- [x] close button -> fermer

### 3.9 Télécharger les données
- [ ] ~~Coquille dans le log: "This could take a while, plase wait" -> "..., please wait"~~ #450

### 4.1 Carte
- [x] la liste déroulante de PixOp n'est pas traduite.

#### 4.2.1 Validation des géométries
- [ ] bouton dans la boîte à outils -> Validation de géométries
- [x] titre du pop-ip -> Outil de validation des géométries
- [x] options pour experts -> Utiliser les résultats...

#### 4.2.2  Analyse de chevauchement
- [ ] La partie select analysis n'est pas traduites

#### 4.2.3 Gérer les sources
- [ ] titre pop-up : Edit source -> Gérer la source / Editar la fuente de datos
- [x] Table of sources depending on selected source -> table des vues dépendantes de la source sélectionnée

#### 4.1.2 Editer les métadonnées des sources
- [x] map-x -> MapX
- [x] titre pop-up: Edit métadata -> Editer les métadonnées des sources

#### 4.1.3 Ajouter une couche source
- [x] titre pop-up: Upload -> Ajouter une couche source

#### 4.3.1 Obtenir un accès provisoire pour éditer une source
- [x] Bouton close pas traduit dans Information de connection

#### 4.4.1 Gérer les vues externes
- [x] Le pop-up n'est que partiellement traduit.
- [x] Il manque le titre, "External views shared in this project" & le bouton save

#### 4.4.2 Définir les roles
- [x] bouton dans la boîte à outils -> Définir les rôles
- [x] Il manque le titre & le bouton save
- [x] Quand les rôles sont sauvés: Rôles mis à jours -> ...à jour
- [x] Le pop-up n'est que partiellement traduit.

#### 4.5 Configurateur de thèmes
- [x] titre -> Configurateur du thème (ou peut être Configuration de l'interface)
- [x] Élements non-visible -> Élements non-visibles

## 5. Système d'invitation et d’adhésion
- [x] Les champs "from" et "to" ne sont pas traduits.

## 6. Outil de récupération de données
- [x] non traduit

## 7. Téléverser par glisser-déposer
- [x] Téléverser: toute la fenêtre n'est pas traduite.

## 8. Story maps engine
- [ ] Slide -> In spanish should be "Diapositiva". In french ?
- [ ] Slide classes (card, text-right ....).
- [ ] In edition mode: all in modules "Insert table", "Insert image" and "Insert video".

## 9. Map composer
- [ ] All terms in the module.

## 10. Draw geom tool
- [x] All tooltips when mouse hover on buttons.

## 11. Views categories pop-up
- [ ] All terms

## 12. Hands on table
- [ ] Clear filter
- [ ] Export CSV

## Autres
- [ ] Les barres de progression ne sont pas traduites.
- [ ] Les logs ne sont pas traduits.
- [ ] Le bouton "Configurer la vue" devient "Editer la vue (dans l'en tête). Problème d'ordre général entre les termes "Configurer" et "Editer" qui semblent être des synonymes mais qui s'alternent (avec les vues, les dashboards et story maps).
- [x] Dans dict_main:  "id": "dev" -> "fr": "Développement"
- [x] Changer MAP-X en MapX dans les emails de bot@mapx.org #241 
- [x] Dans les formulaires, le texte "Value must be at least 3 characters long" n'est pas traduit.

**Comment by MarionPlanque** [comment]
### 5. Story map tool

- The story map schema editor is not translated (except from "Map position" and "update using map parameters"

**Comment by fxi** [comment]
@PierreLacroix : for the translation of the disclaimer, do I translate this myself or should I wait on an official translation ? 
Thanks.

**Comment by PierreLacroix** [comment]
I will translate it

**Comment by antobenve** [comment]
I've updated the list by adding few new terms and by assigning the "done" status to some of the existing ones.
