### ISSUE TITLE
PIckolor color-picker road map

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#392]
### Description
Color picker "Pickolor" is s general purpose color picker and dynamic palette creator for data visualization. Target user is data scientists with at least basic understanding of data visualization and color theory. 
Pickolor is quite basic now, but will envolve to cover as much cases as possible.

---

### To do

- [ ] Programmatic methods to retrieve palette for automatic input filling or rules creation
- [x] Add a id to refer to last used palette in given context. In MapX, save palette by view.
- [x] Remove duplicated colors from divergent colors ramp.
- [ ] Don't apply divergent when random is selected
- [x] Add text input in colors slider for faster selection
- [ ] Color shifting should go both sides.
- [ ] Add a bunch of standards palettes
- [ ] Add CRUD operations on users' palettes
- [ ] Add distance evaluation to measure quality of the generated palette. [ already done using chroma.js, but not visible in UI ]
- [ ] Simplify single color selection : add basic non-paletted colors set, e.g. macOs pencil color

---

### Current interface

![image](https://user-images.githubusercontent.com/1196833/51964817-f27cb000-2467-11e9-9626-0dd4a988fa6b.png)

### Linked issues

#391

**Comment by thomaspiller** [comment]
@fxi As pixop has been set aside in MapX version 1.7.1, is this roadmap still valid or is the development of pixop abandoned?

**Comment by fxi** [comment]
I don't think pickolor (pixop is for pixels operations such overlaps or highlights) will be maintained: to much work left to have something interesting. 

We can close this issue.
