### ISSUE TITLE
rev. 1.5.40.3 testing

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#410]
Here are the results of the tests done on my local stack.

#### Blocking bugs
- [x] Story maps: views are not always displayed in story maps
```
common.bundle.js:formatted:6924 GET http://api.mapx.localhost:8880/get/view/[object%20Object] 500 (Internal Server Error)
```
- [x] File input: importation in DB fails for KML files whether it's a single or a multi-layer dataset #255

```
Upload done. Importation in DB, please wait, this could take a while...
Conversion using ogr2ogr : please wait ...
FAILURE:
Unable to open datasource `1553010028821_test.kml' with the following drivers.
```
- [x] File input: importation in DB returns an error for GPX files because OGR/GPX driver has not been built with read support. Expat library is required. #255
- [x] File input: when uploading a Shapefile with missing .prj file, ogr2ogr doesn't return an exit and the import is considered as successful in MapX. The source is therefore listed in mx_sources and in the interface without being present in the database.
**Possible solution**: do a test at the end of the process, if the table has not been added to the database, revert to the initial state.

#### Non-blocking bugs
- [ ] Area of visible feature: the placeholder is too long and goes beyond the box
![image](https://user-images.githubusercontent.com/19908801/54613859-bb844d00-4a5b-11e9-9bd7-85652c269b48.png)
- [ ] Area of visible features: there's an error when features are not polygons
```
Uncaught TypeError: Cannot read property 'geometry' of undefined
```
- [ ] Define roles: MapX needs to be refreshed to see new members
- [x] Edit view: remove "_mx_valid" from secondary attributes

----
Chrome 72.0.3626.121
Windows 10 Pro
All add-ons disabled

**Comment by antobenve** [comment]
Hi, this is the result of a further test with app v1.5.40.3 and api v1.5.40.5:
- The upload module was tested for import/export of source layers: available in next comment.

- Furthermore, the following bugs are reported in priority order:
#### Non-blocking bugs:
- [ ] Filter features on map through legend: Active selections are not taken into account when a new selection is made.
To test this, try selecting more than 1 item from the legend. When the second one is selected, the first one is not considered anymore. When only one of them is removed, it is like all selections were removed.
The filter process works fine from pop-up window.

#### Lower priority bugs/noticed improvable things
- [ ] Story maps: slide content rule ('Value must be at least 3 characters') is not applied: the story map can be saved anyway. -> Suggestion: remove rule.
- [ ] Click on orange triangle related to metadata check: "Source missing" should be "Missing source" for coherency.
- [ ] Temporary access to db: At the end, the edited layer is displayed on map although the view is not toggled on -> Suggestion: toggle the view on too.


#### Previously reported low priority bugs that are still relevant
- [ ] geoserver faults already in #404 
- [ ] mx_logs faults already in #405 
- [ ] 'source_metadata' is not translated into any language in metadata window when clicking "i" in views' panel. Already in https://github.com/unep-grid/map-x-mgl/issues/393#issuecomment-464136752
- [ ] language change: text as mouse hovers the DIAF star doesn't display in new language until the page is refreshed after the language is changed. Already in #393

**Comment by antobenve** [comment]
### Import/Export evaluation api 1.5.40.5

format | import d&d | import file | export as gpx | export as kml | export as shp | export as gpkg | export as geojson
-- | -- | -- | -- | -- | -- | -- | --
gpx | Y | N 2 | N 1 | Y | Y | Y | Y
kml | Y 3,5 | Y * | N 1 | Y ** | Y **(dd) | Y **, 4(t) | Y **, 4(t)
shapefile | Y | Y * | N 1 | Y **(dd) | Y | Y | Y
gpkg | N 1 | Y | N 1 | Y ** | Y | Y | Y
geojson | Y | Y | N 1 | Y ** | Y | Y | Y

#### Legend:
dd: The mentioned problem only occurs if the exported file was imported through the drag and drop method
t: The mentioned problem only occurs if the exported file was imported through the Toolbox method.

##### Main remarks:
- [ ] 1) Not implemented
- [ ] 2) Failed with this message: 
`Failed. Verify your logs (no logs in docker nor console)`
- [ ] 3) KML specific columns are removed.
- [ ] 4) If the KML file was uploaded through Toolbox, the following warning is sent when exporting as geojson and kml:
`Warning 1: The output driver does not natively support DateTime type for field end. Misconversion can happen. -mapFieldType can be used to control field type conversion.`
The following one is instead sent when exporting it as shapefile:
`Warning 6: Field begin create as date field, though DateTime requested.`
- [ ] 5) Multipolygons consisting of more than 1 polygon are converted into geometry collections when a kml file is imported through drag and drop. (You can test yourself using layer n.4 as mentioned in the list at the end of the issue)
 In this specific case, the following points are relevant:
- Both polygons and collections are displayed in MapX when the user selects 'polygons' in the 'Source geometry type' field in the configuration window of a view (for instance: mx_countries: total polygons: 96, total collections: 173 -> displayed geometries when selecting 'polygons': 269). 
- If the user selects the geometry collections from the configuration window an error is thrown: `Error during methods evaluation :TypeError: Cannot set property 'id' of undefined`
- The summary of distinct values doesn't consider those associated with geometry collections but in the style window every distinct value is taken into account. The user can fully style its view.
- At export: Geometry collections are produced in geojson and gpkg. Shapefiles are exported with the correct multipolygon type. I got both cases when exporting as kml.

##### Layers with null geometries management

- [ ] * Null geometries are imported as collections (KML using Toolbox), null geometry type (SHP using drang and drop) or multipolygon (in all other combinations of formats and methods).
- [ ] ** What was imported as collections is then exported as collections, or not exported at all (exporting as shapefiles)



#### Tested with:
Tested with 2 files that were saved in all formats, published in MapX locally using both methods and later exported through all methods each of them:
1) A light version of mx_countries created through FME and validated in PostGIS and saved initially as .gpkg https://owncloud.unepgrid.ch/index.php/s/N9LcTrAvWFivnNU
2) mx_vector_sp5jo_1jv01_wn9xy_eqyev_u_109 from MapXLocal, exported in all different formats and republished in MapX locally. https://owncloud.unepgrid.ch/index.php/s/Rm7ksmluUkQWAHO

For gpx data we used a demo dataset downloaded from the web. 
3) https://owncloud.unepgrid.ch/index.php/s/r2DksOFS0iV1xEf 

For further investigations on the kml side, we also used 
4) A newly drawn layer with 2 combined polygons and 3 polygons through the MapX drawer. Exported through QGIS as kml file and later re-published in MapX locally: https://owncloud.unepgrid.ch/index.php/s/eDExohhHDcx3WtA

**Comment by thomaspiller** [comment]
Move to #427
