### ISSUE TITLE
Bugs discovered in previous versions of MapX and still unresolved

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#427]
- [x] Temporary access to db: At the end, the edited layer is displayed on map although the view is not toggled on -> Suggestion: toggle the view on too. #414

- [ ] Diaf star tooltip summary : tooltip is not display in new language until the page is refreshed after the language is changed. #393

- [x] Define roles: MapX needs to be refreshed to see new members  #410
- [x] Sort by title: doesn't work properly after changing the UI language - still sort views according to the first language. #257
- [x] Get layer summary -> no stats is generated. The panel that opens is empty. #420
- [x] ~~Area of visible features: the placeholder is too long and goes beyond the box~~  #410
![image](https://user-images.githubusercontent.com/19908801/54613859-bb844d00-4a5b-11e9-9bd7-85652c269b48.png)
- [x] ~~"Delete" button in "Manage sources" is not grayed when deletion is not allowed nor the message  "Deletion of a source disabled because at least one view depends on it" is displayed when the button is not active.~~ #420
- [x] ~~Area of visible features: there's an error when features are not polygons~~  #410

```
Uncaught TypeError: Cannot read property 'geometry' of undefined
```
- [x] ~~Metadata (i button) -> Summary of the source -> Title: when the metadata have never been edited, the value of href is "null" instead of "".~~  #416

**Comment by antobenve** [comment]
I'm closing the issue as the only remaining item is not relevant anymore as DIAF is not included in MapX anymore.
