### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#446]
- [ ] The "-" character should be allowed in the view's title in the "Create new view" module.

- [ ] Titles and abstract should be selectable for copy paste. #169
- [ ] Automatically fill the abstract of a view with the abstract of the source layer that is selected. #299
- [ ] Add a legend title field for rasters in the view configuration window. Default value should be "Legend" but it should be editable. #384
- [ ] Symbols' transparency in style is not managed in the same way between legend and map. Adopt the map behavior. #228
- [ ] Allow the pop-up window for map queries to be resized (and moved if possible) without resetting the filter. #176
- [ ] Change filter combination from OR to AND in pop-up window between different attributes. #127

**Comment by antobenve** [comment]
Hi @thomaspiller , can you please add the following item to the list if it makes sense to you as well?
- [ ] Add the "Share" button and all its functions to custom code views.

**Comment by thomaspiller** [comment]
@antobenve I just added your item to the list
