### ISSUE TITLE
General improvements [lower priority]

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#447]
- [ ] X-scroll bar for dashboard would be useful in case of narrow width screens #186 

- [ ] Extend the "zoom to features" function to raster layers as "zoom to raster layer" #171
- [ ] Allow multiple entries for homepage, range and issuance in the metadata. #93
- [ ] Allow joint documents such as pdf files as annexes to a dataset in the metadata #42

**Comment by MarionPlanque** [comment]
@thomaspiller To be added to the list:

- [ ] Add the status of a project (public or private) in the login window or else
