### ISSUE TITLE
Search tool

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#663]
# Search tool

_A search tool that returns a list of items that summarize matched views. A "view" is simply the name MapX gives to the organised document used to describe how to display information. It could contain the configuration for displaying vector layer on a map, fetching remote raster tiles, communicating with WMS server, store tables, text, or basically, anything, but well organised._

### Milestones

- late April: demonstration of a prototype
- late May: initial version for testing
- late June: release in production

### Specs

language:

- Input as text
- Resolve as ISO 2 letters language code [English -> en]
- Used in further steps

text:

- Input as text
- Resolve as tsvector for fulltext search [Extractive of coltan -> {"coltan": 1000, "extractive": 2,"of": 0}]
- Compares to:
  - title of:
    - views
    - sources (vt only)
    - projects
    - shared and external projects
  - source metadata:
    - keywords
    - GEMET keywords (future development #651, 1st semester 2021)

date:

- Input as text
- Resolve as Unix epoch range : one day to illimited [before:2017 -> {"min": 0, "max": 12212323}]
- Compares to:
  - source metadata (except sm):
    - relased_at
    - issued_at
    - start_at
    - end_at
  - view metadata (sm only):
    - date released 
    - date modified

region:

- Input as text
- Resolve as ISO3 or M49 code [Switzerland -> CHE]
- Compares to
  - geographic keywords

typeView (only in the API, not in MapX UI):

- Input as text
- Resolve as 2 letters view code
- Compares to
  - type of view

project (only in the API, not in MapX UI):

- Input as:
  - idProject
  - text
- Resolve as tsvector for fulltext search (similar to text argument) or as project id
- Compares to:
  - project’s id
  - shared and external project’s id (to cover both ways of sharing views between projects in MapX)
  - title of projects
  - title of shared and external projects 

sortBy (to be explored):

- Input as text
  - alphabetical
  - relevance _(TBC for Phase I)_
  - geographical scale
- Resolve as sorting method of the list of views

  
Returns:

- Format JSON
- Content  
  - Request date
  - Host
  - Request metadata
  - Pagination
  - List of summary objects*: 
    - idView
    - view's title (multi lingual)
    - idProject
    - project's title (multi lingual)
    - shared projects titles (multi lingual)
    - type of view (geospatial or story map)
    - date released (source)
    - date modified (source)
    - start date (source)
    - end date (source)
    - geographic keywords (multi lingual)
    - GEMET keywords (multi lingual) (empty until #651 is developed)
    - keywords
    - link to the view (private project -> static mode)

 
_* There is more information returned than what is needed for the search engine in MapX. This is to facilitate the use of the results in external sources e.g. WESR search engine._

### Documentation

A technical documentation should be published in GitHub as it was done for the [SDK](https://github.com/unep-grid/map-x-mgl/blob/master/app/src/js/sdk/README.md).
For the location argument it would be relevant to list all possible values (ISO3 + M49 codes).

### UI

Basic mockup to show how it could look like in MapX.
A few remarks:

- Non-expert users should be targeted. Therefore, the interface should not be overloaded with too many options:
  - 3 inputs: text, location & dates
  - options to sort results (same as sortBy argument ?)
- The `project` and `typeView` arguments should not be included in the interface.
- For the `region` argument, the possible values should be listed in a drop-down list (ISO3 & M49 codes).
- Two options should be offered to users:
  - Add to map
  - Add to current Project (for publishers & admins)
- It would be interesting to indicate for each view listed in the panel:
  - which criteria were used to select the view
  - its geographical scale

![Screenshot from 2021-03-08 11-35-34](https://user-images.githubusercontent.com/19908801/110310169-81266880-8002-11eb-905d-418e82ba3a0b.png)

## Phase II (2022)

For the second phase, improvement of regional search is targeted:

- new inputs:
  - lat/lng (point -> buffer -> polygon)
  - bounding box (polygon)
- new fields to compare to:
  - source bounding box
  - WMS bounding box for raster views

**Comment by thomaspiller** [comment]
The alpha version of the search engine is very promising.
The first series of tests carried out highlighted some improvements that could improve the user experience:

#### Filter by date

- [ ] group the current search options (6) into an "Advanced temporal search options" category that can be displayed via a checkbox. 
- [ ] add a slider (for single date or range of dates) to filter results from a composite array of dates (source, modified, released, start, end). The slider must be located just above the "Advanced temporal search options" category.

#### GUI
- [ ] Improve tab titles:
    1. views => icon =  fa-folder-o & text = Project's views
    2. toolbox => icon = fa-cog & text = Toolbox
    3. search => icon = fa-search & text = MapX catalog

![Screenshot from 2021-05-18 16-31-05](https://user-images.githubusercontent.com/19908801/118669964-7e13d980-b7f6-11eb-830d-6d5a0a157d73.png)

- [ ] Improve placeholders in search boxes:
    1. "views" tab: “Filter views...” => “Filter views within current project...”
    2. “Search” tab: “Enter keywords here...” => “Enter keywords here to search data in the MapX catalog...”
- [ ] Rename terms in the filters panel:
    1. “source keywords” => “Keywords”
    2. “source-geokeywords” => “Geographic keywords”
    3. “Toggle the filters panel” => “Advanced filtering options” or “More filtering options”
- [ ] Geographic keywords should be organised in two sub-categories:
   1. World and Regions (UNEP regions & intermediate regions & sub-regions & custom regions (e.g., “pantropical”))
   2. Countries 
- [ ] Button “+Open/Close” could be a “+Open” button, that would turn into a “-Close” button when the user has opened the view; then it would turn back to “+Open” when the user has closed the view

**Comment by thomaspiller** [comment]
For mid-July, write:

- [ ] a page in the Wiki to explain how the search tool works (targeted for non-experts)
- [ ] a technical documentation for developers on the use of the API:
    - description of indexes
    - link to MeiliSearch documentation
    - specificities of MapX in addition to MeiliSearch
   
This task is for @thomaspiller

**Comment by fxi** [comment]
"Add two attributes in the index .. project ids .. project names", grouped in an array  `[{id_project:...,description:...,title:...,origin:'project'/'exported'/imported}]`. In the search tool, not returned by default, but present in indexes and fetchable with the api.

**Comment by thomaspiller** [comment]
@PierreLacroix After discussion with @fxi, it is possible to add a route in the API to trigger the update of the indexes. This route would only be available to superusers to be used in exceptional circumstances. In general, the indexes are updated automatically every hour and this operation takes about 1 minute. That being said, should we go with this additional development?

**Comment by PierreLacroix** [comment]
@thomaspiller Thanks a lot for the clarification. One hour frequency is really fine. Let's keep it like this.

**Comment by thomaspiller** [comment]
I just added a new page in the [wiki](https://github.com/unep-grid/map-x-mgl/wiki/Search-tool) explaining how the search tool works in the MapX interface.
I will write the technical documentation for developers on the use of the API in the coming days.

**Comment by thomaspiller** [comment]
This new tool has just been released in the prod version of MapX.
The technical documentation for developers on the use of the API will be released shortly.
